### ISSUE TITLE
TypeBox no longer requires explicit configuration of kind and modifier keywords

### ISSUE THREAD

**Issue by sinclairzx81** [fastify/fastify-type-provider-typebox#19]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi. Just a heads up. I've recently published a new version of TypeBox that should mitigate the need to configure AJV for the `kind` and `modifier` keywords. As of `@sinclair/typebox@0.24.0`, the `kind` and `modifier` keywords have been replaced as symbol property keys. This seems to sidestep the AJV `strict` checks allowing TypeBox schemas to be used without any explicit configuration.

### Before

```typescript
const StringKind = Symbol('StringKind')

const T = {
   kind: StringKind
   type: 'string'
}
```

### After

```typescript
const Kind = Symbol('TypeBox.Kind')

const T = {
   [Kind]: 'String' // AJV should ignore properties defined as symbols
   type: 'string'
}
```
The TypeBox type provider will continue to function with this existing `kind` and `modifier` configuration, however it may be good to remove the `ajvTypeBoxPlugin` export and update the documentation accordingly.

### Current

```typescript
import Fastify from 'fastify'
import { ajvTypeBoxPlugin, TypeBoxTypeProvider } from '@fastify/type-provider-typebox'

const fastify = Fastify({
  ajv: {
    plugins: [ajvTypeBoxPlugin]
  }
}).withTypeProvider<TypeBoxTypeProvider>()
```

### Update

```typescript
import Fastify from 'fastify'

import { TypeBoxTypeProvider } from '@fastify/type-provider-typebox'

const fastify = Fastify().withTypeProvider<TypeBoxTypeProvider>()
```

**Comment by sinclairzx81** [comment]
@mcollina Yup, just preparing one now for review :)

**Comment by sinclairzx81** [comment]
@mcollina Submitted on https://github.com/fastify/fastify-type-provider-typebox/pull/20

**Comment by simonplend** [comment]
@sinclairzx81 This is a really nice improvement 👌🏻
