### ISSUE TITLE
Can't register a plugin using generics - TypeBoxTypeProvider

### ISSUE THREAD

**Issue by rubenferreira97** [fastify/fastify-type-provider-typebox#2]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

next

### Plugin version

0.1.0-beta.0

### Node.js version

16

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

Trying to assign a generic type that uses `TypeBoxTypeProvider` for plugins.

### Steps to Reproduce

```TS
type TypeBoxPluginAsync =
FastifyPluginAsync<Record<never, never>, RawServerDefault, TypeBoxTypeProvider>;

const server = fastify({
  ajv: { plugins: [ajvTypeBoxPlugin] },
}).withTypeProvider<TypeBoxTypeProvider>();

const aPlugin: TypeBoxPluginAsync = async (server) => {};

/* Type 'TypeBoxPluginAsync' is not assignable to type 'FastifyPluginCallback<Record<never, never>, Server, FastifyTypeProviderDefault>'. */
server.register(aPlugin); 
```

### Expected Behavior

No error.

**Comment by RafaelGSS** [comment]
Why are you trying this approach? What is the use-case? The idea of `TypeProvider` is just avoiding the necessity to declare request/response types more than once regardless of the scope.

**Comment by rubenferreira97** [comment]
I am using this approach because TypeBoxTypeProvider is not propagated to the fastify instance inside the plugin.

Example: 

```
const fastify = fastify({
  ajv: { plugins: [ajvTypeBoxPlugin] },
}).withTypeProvider<TypeBoxTypeProvider>();

const aPlugin: FastifyPluginAsync = async (fastify) => {
   //fastify here has the generic FastifyTypeProviderDefault
   fastify.get('/', {
    schema: {
      body: Type.Object({
        x: Type.String(),
        y: Type.Number(),
        z: Type.Boolean()
      })
    }
  }, (req) => {
    // The `x`, `y`, `z` types are not automatically inferred. They are any.
    const { x, y, z } = req.body
  });
};

fastify.register(aPlugin); 
```

**Comment by rubenferreira97** [comment]
Is this a `fastify` or a `type-provider-typebox` bug? Or both? In another words, should a plugin infer the TypeProvider? Should a developer be able to specify the type (first post example) with no problem?

The second problem does not throw a error by changing this:

```TS
export interface TypeBoxTypeProvider extends FastifyTypeProvider {
  output: this['input'] extends TSchema ? Static<this['input']> : never
}
```

to:

```TS
export interface TypeBoxTypeProvider extends FastifyTypeProvider {
  output: this['input'] extends TSchema ? Static<this['input']> : unknown
}
```
Since `FastifyTypeProvider` expect a `unknown`, `never` seems to break this.
However I don't know if this would break other stuff. Any idea?

**Comment by RafaelGSS** [comment]
> y: Type.Number(),
>         z: Type.Boolean()
>       })
>     }
>   }, (req) => {
>     // The `x`, `y`, `z` types are not automatically inferred. They are any.
>     const { x, y, z } = req.body
>   });
> };
> 
> fastify.register(aPlugin);

I have tested this change locally and doesn't seem to work as well. To be honest, it should be inferred once the `withTypeProvider` would return the `FastifyInstance` with the TypeProvider bind, it's not working.

@sinclairzx81 @fastify/typescript any clue?

**Comment by sinclairzx81** [comment]
@RafaelGSS Have these packages been published anywhere? What's the easiest way to create a repro?

**Comment by sinclairzx81** [comment]
@RafaelGSS This seems to be working as expected

```typescript
// npm install "https://github.com/fastify/fastify.git#next" --save
// npm install "https://github.com/fastify/fastify-type-provider-typebox.git" --save
// npm install @sinclair/typebox --save

import Fastify, { FastifyPluginAsync }  from 'fastify'
import { TypeBoxTypeProvider } from '@fastify/type-provider-typebox'
import { Type }                from '@sinclair/typebox'


const aPlugin: FastifyPluginAsync = async (fastify) => {       // FastifyTypeProvider
    fastify.withTypeProvider<TypeBoxTypeProvider>().get('/', { // remap to TypeBoxTypeProvider
        schema: {
            body: Type.Object({
                x: Type.String(),
                y: Type.Number(),
                z: Type.Boolean()
            })
        }
    }, (req) => {
        const { x, y, z } = req.body // Now works
    });
};


const fastify = Fastify()
fastify.register(aPlugin)
```
I think there was some plans to make it a bit easier to supply the provider as a generic argument across `FastifyInstance` and `FastifyPluginAsync` types, which would permit the following.
```typescript
const aPlugin: FastifyPluginAsync<{TypeProvider: TypeBoxTypeProvider }> = async (fastify) => { ... }
```
But I believe this was pending quite a few refactorings.

**Comment by RafaelGSS** [comment]
Actually, I felt that once you have registered the app `withTypeProvider` you shouldn't really do it in all the contexts, you know?

> I think there was some plans to make it a bit easier to supply the provider as a generic argument across FastifyInstance and FastifyPluginAsync types, which would permit the following.

Definitely, we should have it. In meanwhile, I think that we need to update the docs to specify this behavior until we have the above feature. Thank you

**Comment by sinclairzx81** [comment]
@RafaelGSS Sure, I actually left a couple of comments on this on the original PR https://github.com/fastify/fastify/pull/3398#issuecomment-954443194 but think some additional design work would need to be carried out before properly implementing generic signatures for plugins.

It's somewhat possible to implement this today however....

```typescript
// -------------------------------------------------------------------------------------
// FastifyPluginAsync2
// -------------------------------------------------------------------------------------

export interface FastifyPluginAsyncParameters<
    Options extends FastifyPluginOptions = Record<never, never>,
    Server extends unknown = unknown,
    TypeProvider extends FastifyTypeProvider = FastifyTypeProviderDefault
> {
    Options?: Options,
    Server?: Server,
    TypeProvider?: TypeProvider
}

export type FastifyPluginAsync2<T extends FastifyPluginAsyncParameters = FastifyPluginAsyncParameters> = FastifyPluginAsync<T['Options'], T['Server'], T['TypeProvider']>

// -------------------------------------------------------------------------------------
// Updated
// -------------------------------------------------------------------------------------

const aPlugin: FastifyPluginAsync2<{TypeProvider: TypeBoxTypeProvider }> = async (fastify) => {
    fastify.get('/', { 
        schema: {
            body: Type.Object({
                x: Type.String(),
                y: Type.Number(),
                z: Type.Boolean()
            })
        }
    }, (req) => {
        const { x, y, z } = req.body
    });
};


const fastify = Fastify()
fastify.register(aPlugin) // error: But would need to change signatures to support varying provider types.
```
But would need to go through all the interfaces where generic types are passed as arguments and ensure they can support varying generic arguments.

> Actually, I felt that once you have registered the app withTypeProvider you shouldn't really do it in all the contexts, you know?

Yeah, unfortunately, the provider types don't propagate globally. Users can remap a context to use one or more of the providers (for example, typebox and json-schema-to-ts can be used in the same application), but they will need to specify which for their given context.

**Comment by RafaelGSS** [comment]
Ok, I have opened an issue in the Fastify to keep tracking of it.
