### ISSUE TITLE
TypeCompiler could fill defaultValues

### ISSUE THREAD

**Issue by semoal** [fastify/fastify-type-provider-typebox#25]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Og. issue: https://github.com/sinclairzx81/typebox/issues/203
#### Antecedents
Before the last changes to TypeBox and this plugin, using the `ajvPlugin` was possible to define something like this:

```ts
const DEFAULT_PAGINATION = Type.Object({
  limit: Type.Number({ default: 10 }),
  page: Type.Number({ default: 0 }),
});
```

And it was auto-filled on the `req.query` object, this was super easy to build `/search` endpoints where usually the first request you set this fields by default and if you need to paginate then, you pass the params.

#### Actual

Now, this doesn't work anymore and it crashes even if you pass a number to the querystring:

```bash
errors: [
    {
      schema: { default: 0, type: 'number', [Symbol(TypeBox.Kind)]: 'Number' },
      path: '/page',
      value: undefined,
      message: 'Expected number'
    },
    {
      schema: { default: 10, type: 'number', [Symbol(TypeBox.Kind)]: 'Number' },
      path: '/limit',
      value: undefined,
      message: 'Expected number'
    }
  ]
```

#### Expected

Imho, we should have a way to enable this kind of serialization, (I understand that probably doesn't match the json-schema bible, but it makes much much easier to use and work with the api, removing a lot of duplicated code)

### Motivation

Making it easier to work with this plugin and work more-like other validators/compilers.

**Comment by mcollina** [comment]
JSON Schema Serialization is implemented in https://github.com/fastify/fast-json-stringify. Maybe you'd like to add support for this there?

**Comment by semoal** [comment]
> JSON Schema Serialization is implemented in https://github.com/fastify/fast-json-stringify. Maybe you'd like to add support for this there?

Sorry Matteo, probably didn't explain the case correctly. Technically it should work fine (it does without the new compiler). This is the JSON schema generated by Typebox:

```json
  {
  "type": "object",
  "properties": {
    "limit": {
      "default": 10,
      "type": "number"
    },
    "page": {
      "default": 0,
      "type": "number"
    }
  },
  "required": [
    "limit",
    "page"
  ]
}
```

Typebox compiler crashes when passed some query params that are numbers, but arrive to fastify as string, or default is not set.  What I understand is that when you set .setValidationCompilator() the `fast-json-stringify` is replaced by the new one, but this new one doesn't match what we expect to do. 

Could we add this kind of things to the new compilator, at least as options that can be enabled/disabled?

**Comment by mcollina** [comment]
I'm sorry but I'm a bit lost. This module is just a pass-through for typebox compiler: https://github.com/fastify/fastify-type-provider-typebox/blob/main/index.ts. I would not touch the actual data. 

As far as I understand, @sinclairzx81 is not planning to support this in the typebox compiler. I don't think this would happen here either, as we do not have the bandwidth to maintain another JSON-Schema validator.

Note that Ajv works great and it applies the default.

Maybe I didn't understand the situation completely.

**Comment by cesarfd** [comment]
Hey guys. So the idea is either we use the new, faster typebox compiler/validator without the default values/auto casting or we use typebox only to generate the schema and use AJV as the compiler/validator.

**Comment by semoal** [comment]
> Hey guys. So the idea is either we use the new, faster typebox compiler/validator without the default values/auto casting or we use typebox only to generate the schema and use AJV as the compiler/validator.

That was it, I’m sorry if I didn’t explain correctly, Spain’s temperature probably killed my ability to explain correctly haha 

I’m saying that if we accept that Typebox just compiles but not casts or applies default values at least we should mention that in the docs, since it’s not a perfect replacement of typebox + ajv

**Comment by cesarfd** [comment]
> > Hey guys. So the idea is either we use the new, faster typebox compiler/validator without the default values/auto casting or we use typebox only to generate the schema and use AJV as the compiler/validator.
> 
> That was it, I’m sorry if I didn’t explain correctly, Spain’s temperature probably killed my ability to explain correctly haha
> 
> I’m saying that if we accept that Typebox just compiles but not casts or applies default values at least we should mention that in the docs, since it’s not a perfect replacement of typebox + ajv

Yeah, kind of familiar with these temperatures here in BCN :P

Correct, we should not assume Typebox is going to do these. I was preparing a switch to Fastify v4 and I assumed Typebox is going to be the default schema engine for Fastify so I started migrating from fluent-json-schema as AJV 8 was giving weird error messages with the schemas generated by fluent.

My setup is kind of complicated with several different big schemas for both request and reply, I can't migrate so easily.

**Comment by sinclairzx81** [comment]
Hi all !

Just reading through here. I think it's important to make more clear that the new `TypeCompiler` is optional and not intended to supplant `Ajv` (as it only supports a subset of the JSON schema specification). I think for most cases, the preference will be to continue using `AJV` as it's is exceptionally fast and provides the full implementation of the JSON Schema specification. The `TypeCompiler` is best used in instances where it may be beneficial to squeak out additional performance in high message throughput applications (such as when using `fastify-websocket`)

## Auto Assignment for Default Values

TypeBox treats `default` as pure metadata and a separate concern to validation. Additionally, it preferences making mutable assignment on values explicit with the design largely informed by the following

https://json-schema.org/understanding-json-schema/reference/generic.html

> The default keyword specifies a default value. This value is not used to fill in missing values during the validation process. Non-validation tools such as documentation generators or form generators may use this value to give hints to users about how to use a value. However, default is typically used to express that if a value is missing, then the value is semantically the same as if the value was present with the default value. The value of default should validate against the schema in which it resides, but that isn’t required.

Based on the original code snippet provided here https://github.com/sinclairzx81/typebox/issues/203, auto `default` property assignment can loosely be achieved with the following which moves `default` property assignment into the route. The `Value.Cast()` function will preserve the `limit` and `offset` parameters passed by the user, or if omitted, will use the `default` to auto assign the missing property. This operation is immutable.

```typescript
import { Type, SchemaOptions } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

// ----------------------------------------------------------------
// Pagination
// ----------------------------------------------------------------

const NumericString = (options: SchemaOptions) => Type.RegEx(/^(0|[1-9][0-9]*)$/, options)

const Pagination = Type.Object({
    offset: NumericString({ default: '0' }),
    limit: NumericString({ default: '64' })
})

// ----------------------------------------------------------------
// Route
// ----------------------------------------------------------------

server.get('/items', {
  schema: {
     querystring: Type.Partial(Pagination) // Partial<Pagination>
  }
}, (req, res) => {
   const { offset, limit } = Value.Cast(Pagination, req.query)
   // { offset: string, limit: string }
})
```
## Type Provider Auto Property Assignment

So, I've had a look at this this morning, and while It would be technically possible to implement similar logic inside the Type Provider to achieve alignment with `Ajv({ useDefaults: true })`, the implementation would add a significant amount of complexity to this provider to do correctly. As such, I think the best course of action for now would be to.

- Generally make more clear in the documentation that `TypeCompiler` is optional.
- Mention that `default` property assignment is not supported by the `TypeCompiler`
- Optional: Provide minimal documentation on the above `Value.Cast()` allow for explicit `default` property assignment.

Hope that helps!
S

**Comment by StepanMynarik** [comment]
> Hello @sinclairzx81, is there any way to add default value with optional field?

I was just tackling this issue when validating **env** using Typebox.

From my understanding there is only one way to have Typebox add missing properties and initialize them with their schema defined defaults.

- The property must not be marked optional. It must be required.
- Set the property _default_ value
- Use `Value.Cast` **BEFORE** using the object. This will add the missing properties and initialize them with their respective defaults.

Perhaps @sinclairzx81 can correct me if I'm wrong.

**Comment by sjoerdvanBommel** [comment]
For anyone running into this, I wrote a preParsing hook that automatically sets defaults based on the schema. **Make sure the schema type is not optional, or the default will not be filled.** 

```ts
import fp from 'fastify-plugin';
import { Value } from '@sinclair/typebox/value';
import type { FastifyPluginAsync, FastifyRequest } from 'fastify';
import type { TSchema } from '@sinclair/typebox';

export const schemaDefaultsPlugin: FastifyPluginAsync = fp(async (fastify) => {
  fastify.addHook('preParsing', async (request: FastifyRequest) => {
    // For GET requests, get default values from querystring schema
    if (request.method === 'GET' && request.routeSchema?.querystring) {
      request.query = Value.Cast(
        request.routeSchema.querystring as TSchema,
        request.query,
      );
    }

    // For POST requests, get default values from body schema
    if (request.method === 'POST' && request.routeSchema?.body) {
      request.body = Value.Cast(
        request.routeSchema.body as TSchema,
        request.body,
      );
    }
  });
});
```
