### ISSUE TITLE
Export TypeBox `Type.*` object on provider

### ISSUE THREAD

**Issue by sinclairzx81** [fastify/fastify-type-provider-typebox#29]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Hi. I'm wondering if it might be possible to export the TypeBox `Type.*` namespace on this provider. This to simplify usage and avoid an additional import of `@sinclair/typebox`. 

### Motivation

I think in the context of Fastify, having the `Type.*` namespace be exported on the `@fastify/type-provider-typebox` package would be quite nice for the end user as the provider would export all the necessary infrastructure without requiring an additional import of `@sinclair/typebox`. 

### Example

```bash
$ npm install fastify @fastify/type-provider-typebox --save
```

```typescript
import { Type, TypeBoxTypeProvider } from '@fastify/type-provider-typebox'
import Fastify from 'fastify'

Fastify().withTypeProvider<TypeBoxTypeProvider>().get('/', {
  schema: {
    querystring: Type.Object({
      offset: Type.Number(),
      limit: Type.Number()
    })
  }
}, (req, res) => {
  const { offset, limit } = req.query
})
```

**Comment by RafaelGSS** [comment]
I'm not sure if I concur. Usually, when you have a library that wraps another library, it's common sense to install both and the user will manage the version of the library. For instance, `knex` doesn't include `pg` as a dependency, you should install it if you want to use Postgres.

Also, how would it work with `typebox` updates? It will be a `peerDependency` or this module will need to be updated every time `typebox` gets a new version? I'm not a fan of attaching `typebox` as a dependency of this module (even knowing it's required to install to use it properly), because, every time `typebox` will get a breaking change, this module will need to be updated too, making the maintenance a bit harder/annoying.

**Comment by sinclairzx81** [comment]
@RafaelGSS Hi, the thinking here would be that the provider would just export `Type.*` namespace for convenience but remain as a `peerDependency` (allowing users to manage the TypeBox version they need). Also note that when a user installs `@fastify/type-provider-typebox`, npm will automatically install TypeBox if the user hasn't already done so.

```bash
$ npm install @fastify/type-provider-typebox

# no need to install @sinclair/typebox separately 
$ cat node_modules/@sinclair/typebox/typebox.js 
```
> Note this is different to `knex` where `pg` and other db drivers are flagged as `optional` dependencies via `peerDependencyMeta` ([reference](https://github.com/knex/knex/blob/master/package.json#L78-L100)). This makes sense in the `knex` case, but for providers; because they are intrinsically coupled to only one inference lib, I feel the current non-optional `peerDependency` configuration is correct.

Overall, I do think having the provider export `Type.*` would be quite ergonomic for users. It may have also been the expectation going by the Type Provider code example in the Fastify 4.0 blog post. https://medium.com/@fastifyjs/announcing-fastify-v4-release-candidate-2b6be6edf196

Exporting the type builder may be applicable for other kinds of providers too.

```typescript
import { TypeProviderJsonSchemaToTs } from '@fastify/type-provider-json-schema-to-ts'

import { Type, TypeProviderTypeBox } from '@fastify/type-provider-typebox'

import { z, TypeProviderZod } from '@fastify/type-provider-zod'

import { t, TypeProviderIoTs } from '@fastify/type-provider-io-ts'

import { yup, TypeProviderYup } from '@fastify/type-provider-yup'
```
Open to thoughts!

**Comment by RafaelGSS** [comment]
I'm just worried about potential breaking changes and the module ownership. For instance, I can see a future when the users will open an issue in `fastify-type-provider-typebox` reporting a bug inside `Type` instead of opening the issue in the `typebox` repository.  

I can agree that break changes are not blocking, as if this happens even though I don't export `Type`, this module will still be affected, so I withdraw this argument. However, the module ownership concern is still valid.

**Comment by sinclairzx81** [comment]
@RafaelGSS Apologies for the late reply on this.

I wouldn't have assumed users would get the impression that the `Type.*`  namespace is somehow the responsibility of the Fastify organization if it was communicated in the documentation that this package simply re-exports the namespace for convenience (and by consequence, any errors with `Type.*` would suggest the error resided in the TypeBox library). However, with this said, I can imagine this package possibly exporting a variety of extension types that are more aligned with the common usages of Fastify in future.

The following extended types would help to resolve often asked issues on the TypeBox repository. With `StringEnum` and `Nullable` very common queries for Open API users, and the `Date` type queried about https://github.com/fastify/fastify/discussions/3357

```typescript
import { TypeBuilder, Static, TSchema } from '@sinclair/typebox'

export class FastifyTypeBuilder extends TypeBuilder {
    
   // ------------------------------------------------------------------
   // Date type that automatically infers as type Date
   // ------------------------------------------------------------------
   
   public Date() {
      return this.Unsafe<Date>({ type 'string', format: 'date' })
   }

   // ------------------------------------------------------------------
   // Nullable<T> for OpenAPI / Swagger
   // ------------------------------------------------------------------
   public Nullable<T extends TSchema>(schema: T) {
      return Type.Unsafe<Static<T> | null>({ ...schema, nullable: true })
   }
   
   // ------------------------------------------------------------------
   // StringEnum Type for OpenAPI / Swagger
   // ------------------------------------------------------------------
   
   public StringEnum<T extends string[]>(values: [...T]) {
      return Type.Unsafe<T[number]>({ type: 'string', enum: values })
   }
}

export const Type = new FastifyTypeBuilder() // re-export new TypeBuilder
```
With the following usage
```typescript
import { Type, TypeBoxTypeProvider } from '@fastify/type-provider-typebox'

Fastify().withTypeProvider<TypeBoxTypeProvider>().post('/', {
   schema: {
     body: Type.Object({
        option: Type.StringEnum(['a', 'b', 'c']),
        created: Type.Date(),
        optional: Type.Nullable(Type.String())
     })
   }
}, (req, res) => {
    req.body     // 'a' | 'b' | 'c'
    req.created  // Date
    req.optional // string | null
})
```
I should also provision that extending TypeBox's `TypeBuilder` in this way is actually a design intent in the TypeBox library as it's intended to be highly embeddable into libraries in exactly this way. For a reference example of this usage, you can refer to [this](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwL5wGZQQhwDkAAgM7AAmGA7sAHa1QD0AxhIzFAIbswSAKFCRYiOAHUMAIwDKGKADdg7LLgJFSlGvSYtWFRUsXDR0eEmkyAwgBtgGbjnyFi5KrQbNFHB08EhIVZWOABaCMio6JjYuPiExPjg0JsuHn4YFPCk3Lz8gqigzkYKeDTuPgE4AF4UdAwAOgqMgQAKBCE4brgjZUUALkQuntGSXmpqEiG0TEaAMQBXRgFgLjaAbVmmgDlFkBlFNoBKABp6ub2Do+OAXXPtxqvDqBPjke7sIWx37ML-gGAsLZBTKVQYP5AqHQuLFLhlXrGcG1OCMehSWSglRqNotKowX59bFNEAYGAACwg1Da40mJHObXY-m4AElqOdeOcZMdagA+YajEKjUYAH2F4rFwpFHzgQvFcEl8u6ip6AGpInAwLw+CAKHA2rwhox9i8uUaTYp3oLQvKVbaZXKJUq1RrlsAAI6LLBMxzOXTcYB4RxQB02iWhpXqiJwUkUqmo3ikuBMPCKKAYaiuLQlVpZa2hiOjKNhODpmCLKCMZOMVNQdOZ3h6gAGxuuUCbhZ60tGZYrVd4cFVcBkcG+vyFMMnU+y9l9WQnU8XQLhpXgPoCKLRdAxtmZMFx6Xx5xI5JgMDAAxCjWvjRIvxKCPTFEWdngdV4dF4wDXe8a7F4dh2DSExTOcACM4HvI6CrOrBTpKtK0F2nBzrIS60bagA5vsAR6o2+qxpS1BDGUUBMJhHLmm2ZqohaUBQWGMEoShYrZF2zEocWMZkkRCZJimaYZlmxA5vibHKuJg4ak+L7wMAzati8TZAA) typescript link where `@sidewinder/contract` re-exports a extended `TypeBuilder` to include a `Type.Contract()` method for specifying RPC contracts.

Ultimately, it's the call of Fastify as to whether re-exporting `Type.*` makes sense in the context of this (or other) provider, but do feel there is both ergonomic as well as technical rationales for considering it. Also given the nature of this provider, I wouldn't be adverse to helping keep the package up to date as well as helping to field issues submitted by users (as I already field a few Fastify+TypeBox related issues submitted to the TypeBox project)

**Comment by RafaelGSS** [comment]
> However, with this said, I can imagine this package possibly exporting a variety of extension types that are more aligned with the common usages of Fastify in future.

> Ultimately, it's the call of Fastify as to whether re-exporting Type.* makes sense in the context of this (or other) provider, but do feel there is both ergonomic as well as technical rationales for considering it.

Thanks for the whole explanation of your point of view, that's indeed a fair point and I can concur with exporting `Type.` and its implementation such as `Date`.

**Comment by sinclairzx81** [comment]
@RafaelGSS Ok great! I'm thinking that exporting a custom `FastifyTypeBuilder` is probably the way to go. Outside of `Date` though, can you think of any other useful types that would be good to export on the builder?
