### ISSUE TITLE
Add Support Typebox 0.25.x

### ISSUE THREAD

**Issue by robindiddams** [fastify/fastify-type-provider-typebox#44]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Support Fastify 1.25.x so that we can use the latest typebox types.

### Motivation

Fastify 1.25 adds some new types that we would like to use

**Comment by kibertoad** [comment]
@robindiddams Would you be open to send a PR for this? Don't forget to include tests.

**Comment by climba03003** [comment]
Do you means support `typebox@0.25.x`, or support `typebox` for `fastify@1`?

**Comment by robindiddams** [comment]
> Do you means support `typebox@0.25.x`, or support `typebox` for `fastify@1`?

yes my bad

**Comment by climba03003** [comment]
You can check how to setup `ajv` in [`typebox` document](https://github.com/sinclairzx81/typebox#ajv).

**Comment by james-gardner** [comment]
I'm confused. Does this propose to resolve:

```
npm ERR! Found: @sinclair/typebox@0.25.9
npm ERR! node_modules/@sinclair/typebox
npm ERR!   @sinclair/typebox@"^0.25.9" from the root project

npm ERR! Could not resolve dependency:
npm ERR! peer @sinclair/typebox@"^0.24.1" from @fastify/type-provider-typebox@2.3.0
```

?

**Comment by HassanBahati** [comment]
@RafaelGSS shouldn't this be closed as it appears to be completed
