### ISSUE TITLE
Does not type check if withTypeProvider is not fluent

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-type-provider-typebox#55]
Consider the following:

```typescript
import Fastify from 'fastify';
import { TypeBoxTypeProvider } from '@fastify/type-provider-typebox';
import { Type } from '@sinclair/typebox';

const server = Fastify();

server.withTypeProvider<TypeBoxTypeProvider>();

server.post('/', {
  schema: {
    body: Type.Object({
      name: Type.String()
    })
  }
}, async (request, reply) => {
  const { name } = request.body;
  return { hello: name };
})

server.listen({ port: 3000 })

```

This does not work but it errors with:

```
server.ts:16:11 - error TS2339: Property 'name' does not exist on type 'unknown'.

16   const { name } = request.body;
             ~~~~
```

However if we inline the route definition and `withTypeProvider` call it works:

```typescript
import Fastify from 'fastify';
import { TypeBoxTypeProvider } from '@fastify/type-provider-typebox';
import { Type } from '@sinclair/typebox';

const server = Fastify();

server.withTypeProvider<TypeBoxTypeProvider>().post('/', {
  schema: {
    body: Type.Object({
      name: Type.String()
    })
  }
}, async (request) => {
  const { name } = request.body;
  return { hello: name };
})

server.listen({ port: 3000 })
```

**Comment by mcollina** [comment]
cc @sinclairzx81 @Eomm @RafaelGSS

**Comment by SimenB** [comment]
you need to to

```ts
const typeboxServer = server.withTypeProvider<TypeBoxTypeProvider>();
```

or add the `withTypeProvider` call to your initial `Fastify()`

**Comment by RafaelGSS** [comment]
That's correct. We can't mutate the server instance without returning a new instance with the typebox definitions.

A good strategy is always call it in the server creation:

```ts
const fastify = Fastify().withTypeProvider<TypeBoxTypeProvider>()
```

**Comment by sinclairzx81** [comment]
@mcollina Hi!

The TypeProvider setup does require functions to chain in this way. Each call to `withTypeProvider()` will remap the current instance generics and return the mapped instance to the caller for assignment or additional chaining. It's a fairly common pattern for TypeScript developers.

### Type Mapping Statements (An Experiment)

While it's not recommended, you can somewhat tap into TypeScript's control flow analysis to rewrite generic arguments by using [assertion predicates](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates). Just for fun, the following implements assertions to support type mapping providers using statements and control flow narrowing.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgMQIYGcbAGYE84C+c2UEIcA5NhlnhQFD0DGEAdpnOgKZQBuPcALwoaOXAAoAlIwD0MuAFolylarXqNmrdtWM0mMQDoA7sBgALACq4wXAAqlewACY8APNdsAhCAA9P9o4uPAB84tx8PNL0EfxQhpCY4hQyFAA0iPRwnEzmXCCoAFyZ2dkARhDOuMUBhgDyZQBWXEww4ghZpdmsqCBcNTZchgDKMFDArADmUp3ZBNJz9AQZGLisTHDiUFwAjgCuXJgZ22AANriSQiElcCzs8Eg9fYRCcNv7hzCGFVVwcnAQADWnW2MD2UFYiDgeVOpwgxSeXEIS2i-x06IxmKxCj0ojwJjMVkGDggTlcUDcACl0Gxhrl8qhLBBLOgSWTQuEeHForEeAkIEkUukbuh6QVih0uj9qjcujBBsUKBAmi0YOlZqV3ntgNtnMUANoUREUAC6aQ12TApFssGAhwlcERDvltkVmHGUwoLwIGqIGFubEwnR9yzgq3Wmy1n2OXDOFyuNzuHEevSRRGEUcw30q+H+QJBXDBEKhMLhCNTyPmsnk2NrdexuIM+NMFgCbOCFIAWpU20FyWFeVAeVy+Yk2kKMpKcnlxbK4NLigAvQzK5qtdoWx2ppeGd0TaYLUpVxah8MbLa7A5HN6x86XQTXKdJh5b57pm8fLPSv7yfPZUHgpCSClvCr5pii1aKPW0Eweoja0LgBKtsSfbuAAmnsYC9qSHYDiOQ6MIO-KCqkk6dKKM5FHOC5wLgmEriq65Tl0Tq0fRe5TFIhhajqXDODMXTHpWKzoGs56ZjAMZxvej6dM+UKIi8GaXp82a-D+ALAv+haASWXCwqBikhtE9ByLB5kWXB-wACKoFAgJwAAsqgkzAEwpkyJZXmWfQrhMKcdlIiAlR7KcSIAETUE2uDhTcXC+JAsABvcIjRcU4hSAmACC6ARDAqBlGF+gIQAkvcqDrFwlwAGRznALZErY7bksUbh2HA8UwFwrDOOgqUIdh7JQGEvCoKcBzFBV8YPmGuU8DAfWjeNSLAH1OV5XxxViGVmAVUwXBtSEwZLPQoCJS+W14Dt+WVRkl24INHYvCQZCUFFCEMGd0AvgEPj+ChOHks9pDkBQAAC71iDILpcAoVqAzwCgwxUvifeA31QtStJioyzKsqhUDA694OQ3g0ODHDBMKI0NKsAoFEMkjEBI+gaPnVCARE6DYPoBM-moDq5O2CjbMY4uk5wN2zgBFlrD4EQL2g4ulSi0ldFgMQIOUOrDD0PF7MTF1UDUPtks9gDQ0db4XU9X192PUDSAQHsMBgC7xQWKthoTG7aomlbNu9Wb0uDLL+AAPxwMuEzYO4nvoN7rC+6a1zFHsrCAqwEDGJCPr6xjhs8CbSIYVhFtPZ13VB-b5eOwCLu+x75hexQPsu6aAdV316uGCVdKUW4U0rHLw+4KP1yRz3ZWx1AARuPHifJyaqdwOnmfZ7nesJRjMNwOt80FUVeK4Nde1IsI92n5Vg8j2Gt9D3fY-9WIDuhFv7O7-vsCbcfV-7W1ndbbPzwK-YarxL7lWvg-aB99b52BCEAA) (note: inference takes a little while to load in)

```typescript
const server = Fastify()

// -----------------------------------------------------------------------

Fastify.withTypeProvider<TypeBoxTypeProvider>(server)

server.post('/', {
  schema: {
    body: Type.Object({
      name: Type.String()
    })
  }
}, async (request, reply) => {
  const { name } = request.body // ok
  return { hello: name }
})

// -----------------------------------------------------------------------

Fastify.withTypeProvider<JsonSchemaToTsProvider>(server)

server.post('/', {
  schema: {
    body: {
      type: 'object',
      required: ['name'],
      properties: { name: { type: 'string' } }
    } as const
  }
}, async (request, reply) => {
  const { name } = request.body // ok
  return { hello: name }
})

// -----------------------------------------------------------------------

Fastify.withTypeProvider<ZodTypeProvider>(server)

server.post('/', {
  schema: {
    body: z.object({
      name: z.string()
    })
  }
}, async (request, reply) => {
  const { name } = request.body // ok
  return { hello: name }
})

// -----------------------------------------------------------------------

Fastify.withTypeProvider<YupTypeProvider>(server)

server.post('/', {
  schema: {
    body: yup.object({
      name: yup.string().required()
    })
  }
}, async (request, reply) => {
  const { name } = request.body  // ok
  return { hello: name }
})

```
This approach is quite novel, but probably not useful in practice.
Hope this helps!
S

**Comment by mcollina** [comment]
Thanks! I will send a PR to include some of this in the README.

**Comment by thelinuxlich** [comment]
I'm still getting untyped responses 
![image](https://github.com/fastify/fastify-type-provider-typebox/assets/5043/fa426b14-823b-4337-b0b9-7fd4078f7bed)
