### ISSUE TITLE
Support typebox 0.27.8

### ISSUE THREAD

**Issue by Zajozor** [fastify/fastify-type-provider-typebox#71]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Support Typebox 0.27.8, currently we use `"@sinclair/typebox": "^0.26.4"` in `package.json`.

### Motivation

The versions in the meantime have some nifty features :) 

### Example

This example from Typebox docs does not work with the current version 0.26.4:

```
type PointOptions = { }                              // The Type Options

type PointType = { x: number, y: number }            // The Static<T> Type

const Point = TypeSystem.Type<PointType, PointOptions>('Point', (options, value) => {
  return (
    typeof value === 'object' && value !== null &&
    typeof value.x === 'number' && 
    typeof value.y === 'number'
  )
})

const T = Point()

type T = Static<typeof T>                            // <-- throws type error

const R = Value.Check(T, { x: 1, y: 2 })              // const R = true
```

**Comment by mcollina** [comment]
nothing, I just shipped it.
