### ISSUE TITLE
string auto convert to number

### ISSUE THREAD

**Issue by miniboxhaha** [fastify/fastify-type-provider-typebox#82]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.2.0

### Node.js version

18.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

win10

### Description

use fastify with TypeBoxTypeProvider,validate will auto cast sting to number,and auto cast sting to string[]

for example code blow:

### Steps to Reproduce

```
//server.ts
const server = fastify().withTypeProvider<TypeBoxTypeProvider>()
fastify.post<
            { Body: User[] }
        >('/marks', { schema: { body: properties} }, async (request, reply) => {
            try {
                reply.code(200).send()
            } catch (err) {
                reply.code(400).send(err)
            }
        }),

//validate.ts
export const properties = Type.Object({
   timestamp: Type.Readonly(Type.Integer()),
   users:Type.Optional(Type.Array(Type.String()))
})



//testData1:
{
   timestamp:1683687611279,
   users:["tom","jerry"]
}
expect:OK
result:OK

//testData2:
{
   timestamp:"1683687611279",
   users:"tom"
}
expect:False
result:OK
```

**Comment by mcollina** [comment]
This is expected because Fastify creates Ajv with `coerceTypes: "array"` by default: https://www.fastify.io/docs/latest/Reference/Validation-and-Serialization/#schema-validator.

**Comment by miniboxhaha** [comment]
thanks，i will follow the doc
