### ISSUE TITLE
incorrect (and potentially broken) dependency resolution error when installing latest via NPM

### ISSUE THREAD

**Issue by mkgn** [fastify/fastify-type-provider-typebox#89]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.19.1

### Plugin version

3.2.0

### Node.js version

18.12.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

windows 10 build 19044.3086

### Description

as per installation instructions (in this page as well as [fasitfy docs](https://fastify.dev/docs/latest/Reference/TypeScript#json-schema) when you install the package via

    npm i @sinclair/typebox @fastify/type-provider-typebox

it fails with below error. 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @fastify/type-provider-typebox@3.2.0
npm ERR! Found: @sinclair/typebox@0.29.1
npm ERR! node_modules/@sinclair/typebox
npm ERR!   @sinclair/typebox@"^0.29.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @sinclair/typebox@"^0.28.0" from @fastify/type-provider-typebox@3.2.0
npm ERR! node_modules/@fastify/type-provider-typebox
npm ERR!   @fastify/type-provider-typebox@"^3.2.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @sinclair/typebox@0.28.20
npm ERR! node_modules/@sinclair/typebox
npm ERR!   peer @sinclair/typebox@"^0.28.0" from @fastify/type-provider-typebox@3.2.0
npm ERR!   node_modules/@fastify/type-provider-typebox
npm ERR!     @fastify/type-provider-typebox@"^3.2.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### Steps to Reproduce

just follow the documentation and install

npm i @sinclair/typebox @fastify/type-provider-typebox

### Expected Behavior

It should not throw an error and properly setup

**Comment by mcollina** [comment]
Should be fixed in v3.3.0
